In [320]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

In [321]:
df = pd.read_csv('used_car_sell_data.csv')

In [322]:
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [323]:
df = df.rename(columns={'Car Model': 'car_model',
                        'Mileage': 'mileage', 
                        'Sell Price($)': 'sell_price', 
                        'Age(yrs)': 'age'})
df.head()

car_model  mileage  sell_price  age
0    BMW X5    69000       18000    6
1    BMW X5    35000       34000    3
2    BMW X5    57000       26100    5
3    BMW X5    22500       40000    2
4    BMW X5    46000       31500    4

In [324]:
df.shape

(13, 4)

In [325]:
pd.unique(df.car_model)

array(['BMW X5', 'Audi A5', 'Mercedez Benz C class'], dtype=object)

In [326]:
df_le = df.copy()
df_ohe = df.copy()
df_getd = df.copy()

In [327]:
le = LabelEncoder()
ohe = OneHotEncoder()

In [328]:
df_le.car_model = le.fit_transform(df_le.car_model)
pd.unique(df_le.car_model)

array([1, 0, 2])

In [329]:
df_le.head()

car_model  mileage  sell_price  age
0          1    69000       18000    6
1          1    35000       34000    3
2          1    57000       26100    5
3          1    22500       40000    2
4          1    46000       31500    4

In [330]:
df_ohe.car_model = le.fit_transform(df_ohe.car_model)
pd.unique(df_ohe.car_model)

array([1, 0, 2])

In [331]:
df_ohe.head()

car_model  mileage  sell_price  age
0          1    69000       18000    6
1          1    35000       34000    3
2          1    57000       26100    5
3          1    22500       40000    2
4          1    46000       31500    4

In [332]:
dummies = pd.get_dummies(df_getd.car_model)
dummies.head()

Audi A5  BMW X5  Mercedez Benz C class
0        0       1                      0
1        0       1                      0
2        0       1                      0
3        0       1                      0
4        0       1                      0

In [333]:
df_getd = pd.concat([df_getd, dummies], axis=1)
df_getd.head()

car_model  mileage  sell_price  age  Audi A5  BMW X5  Mercedez Benz C class
0    BMW X5    69000       18000    6        0       1                      0
1    BMW X5    35000       34000    3        0       1                      0
2    BMW X5    57000       26100    5        0       1                      0
3    BMW X5    22500       40000    2        0       1                      0
4    BMW X5    46000       31500    4        0       1                      0

In [334]:
df_getd_y = df_getd.sell_price
df_getd = df_getd.drop(columns=['car_model', 'sell_price', 'Mercedez Benz C class'])
df_getd.head()

mileage  age  Audi A5  BMW X5
0    69000    6        0       1
1    35000    3        0       1
2    57000    5        0       1
3    22500    2        0       1
4    46000    4        0       1

In [335]:
reg = LinearRegression()
reg.fit(df_getd.values, df_getd_y)
reg.score(df_getd.values, df_getd_y)

0.9417050937281082

In [336]:
reg.predict([[45000, 4, 0, 0]])

array([36991.31721061])

In [337]:
reg.predict([[86000, 7, 0, 1]])

array([11080.74313219])

In [338]:
reg1 = LinearRegression()
reg1.fit(df_ohe.drop(columns=['sell_price']).values, df_ohe.sell_price)
reg1.score(df_ohe.drop(columns=['sell_price']).values, df_ohe.sell_price)

0.8719970367825953

In [339]:
reg1.predict([[2, 45000, 4]])

array([33336.7721827])

In [340]:
reg1.predict([[1, 86000, 7]])

array([16106.74127344])